provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  llm:
    lang: python3-http-debian
    handler: ./main
    image: localhost:5000/llm:latest
    environment:
      DIAGNOSTICS: "true"
      LOG_DIR: "/tmp/llm_logs"
